version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/London"
    reviewers:
      - "sabihsaleh"
    assignees:
      - "sabih"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "mvn"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/London"
    reviewers:
      - "sabihsaleh@yahoo.com"
    assignees:
      - "sabihsaleh@yahoo.com"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "npm"
