version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "23:07"
      timezone: "Europe/London"
    reviewers:
      - "sabihsaleh@yahoo.com"
    assignees:
      - "sabihsaleh@yahoo.com"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "mvn"
