version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "23:06"
      timezone: "Europe/London"
    reviewers:
      - "sabih.saleh@bca.com"
    assignees:
      - "sabih.saleh@bca.com"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "mvn"
